// <auto-generated />
namespace Tours.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class attachments_passengerphoto_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attachments_passengerphoto_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201712040754439_attachments_passengerphoto_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
